### ISSUE TITLE
Adding Crow Nuget to solution results in "Could not load file or assembly"

### ISSUE THREAD

**Issue by TheOneSock** [jpbruyere/Crow#36]
I had a working OpenTK solution in JetBrains Rider.
- .NETFramework v4.6.2
- C# 6.0

I added the CROW nuget and changed my window class to inherit from CrowWindow instead of GameWindow. And nothing else.

I run and I get;

> System.IO.FileNotFoundException was unhandled
> Message: An unhandled exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll
> Additional information: Could not load file or assembly 'Crow, Version=0.5.6463.31239, Culture=en-US, PublicKeyToken=13516c29fef4602c' or one of its dependencies. The system cannot find the file specified.

In the bin debug folder I have:

- Crow.dll (the same version)
- OpenTk.dll (2.0.0)
- Newtonsoft.Json.dll (not important for this bug report I think)

What am i missing? what else does crow depend on.

**Comment by TheOneSock** [comment]
Ok I found out what the issue was...

by using this atricle: https://www.codeproject.com/Articles/560816/Troubleshooting-dependency-resolution-problems-usi

I found out that for some reason the dll is beeing searched for in the en-US subfolder of the debug folder. (see picture)

![image](https://user-images.githubusercontent.com/18218893/34958166-f974b66c-fa30-11e7-9db2-cf31a7cc1df5.png)

after manually moving the .dll it started to work.

**Comment by TheOneSock** [comment]
Turns out this is because of some of the culture with which CROW is compiled...

If this wouldn't break any other usage you have I would suggest changing [assembly: AssemblyCulture ("en-US")] to [assembly: AssemblyCulture ("")]

for now i will just add an additional build step to copy it there, for I am not well versed enough in this for a clean solution on my side.

**Comment by jpbruyere** [comment]
First of all thank you for your bug report and sorry for my late answer.
I have modified AssemblyCulture as you suggested and will try to release a new nuget package as soon as possible.
