### ISSUE TITLE
The possibility of partnership with the Avalonia project

### ISSUE THREAD

**Issue by insinfo** [jpbruyere/Crow#41]
It would be great for the community if a partnership happens, as Avalonia lacks an Accelerated Hardware API (OpenGL).
Mainly for OpenGL targets like Android, IOS, MacOs, Linux, WASM (WebAssembly)

https://github.com/AvaloniaUI/Avalonia/issues/1387#issuecomment-381389726

**Comment by jpbruyere** [comment]
C.R.O.W. use cairo graphic lib for 2d drawing for now and [vkvg](https://github.com/jpbruyere/vkvg) in the future through Pinvoke calls. For the widget infrastructure, we target quiet the same goals (xaml, styling and templates), we surely have knowledge to share on our experiences.
Answering your request, OpenGL api for toolkit backend lacks multi-threading flexibility, I have tested several arch with GL, and I would not recommend it for high level toolkits, that's where [vkvg](https://github.com/jpbruyere/vkvg) will fill the gap thanks to vulkan, any contributors are welcome.
