### ISSUE TITLE
The 'Hello World' Sample doesn't work for Linux/MONO nor for Windows/.NET

### ISSUE THREAD

**Issue by PloetzS** [jpbruyere/Crow#45]
It's impossible to run the 'Hello world' sample with the description at Crow/wiki/Tutorials/hello-world.

Using **Windows 10 64Bit, Visual Studio 15.9.3, .NET 4.6.1 and OpenTK.Crow NuGet package 0.7.1** I get a running window but also an exception at CrowWindow.cs line 353:
_Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
Parametername: index
   bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   bei System.Collections.Generic.List#1.get_Item(Int32 index)
   bei Crow.CrowWindow.GL_Mouse_Move(Object sender, MouseMoveEventArgs otk_e) in CrowWindow.cs:Zeile 353.
   bei System.EventHandler#1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.NativeWindow.OnMouseMove(MouseMoveEventArgs e)
   bei OpenTK.NativeWindow.OnMouseMoveInternal(Object sender, MouseMoveEventArgs e)
   bei System.EventHandler#1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.Platform.NativeWindowBase.OnMouseMove(Int32 x, Int32 y)
   bei OpenTK.Platform.Windows.WinGLNative.HandleMouseMove(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   bei OpenTK.NativeWindow.ProcessEvents(Boolean retainEvents)
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei OpenTK.GameWindow.Run(Double updateRate)
   bei OpenGL_TestCrow_NuGet.CrowTest.Main() in C:\Data\Misc\MSVS_12.dat\OpenGL-TestCrow-NuGet\OpenGL-TestCrow-NuGet\Program.cs:Zeile 27._

Using **openSUSE 13.2 64Bit, Mesa 10.3.7, Mono Develop 5.10, Mono/.NET 4.5, OpenTK.Crow NuGet package 0.7.1** I do not even get the window displayed - this is the exception:
_X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  156 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  83
  Current serial number in output stream:  81_

**Comment by jpbruyere** [comment]
a quick fix is to replace on line **353** of **CrowWindow.cs**
``` 
    if (ifaceControl [focusedIdx].ProcessMouseMove (otk_e.X, otk_e.Y))
        return;
```
by
``` 
    if (CurrentInterface.ProcessMouseMove (otk_e.X, otk_e.Y))
       return;
```
I'll update the nuget package with the fix, thanks for your report

**Comment by jpbruyere** [comment]
The nuget package has been update with the fix
